---
title: "Building Matrixes from Networks"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Building Matrixes from Networks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r loadLibs}
library(PNetica)
```

# Loading the Langauge Models

```{r setupNetica}
RNetica::SetupDefaultSession()
Language <- as.Pnet(RNetica::local_RNetica_net("LanguagePM.dne"))
Proficiencies <- RNetica::NetworkAllNodes(Language)
Reading <- as.Pnet(RNetica::local_RNetica_net("ReadingTask.dne"))
Writing <- as.Pnet(RNetica::local_RNetica_net("Write2EM.dne"))
Speaking <- as.Pnet(RNetica::local_RNetica_net("SpeakingTask.dne"))
Listening <- as.Pnet(RNetica::local_RNetica_net("ListeningTask.dne"))
EMs <- list(Reading=Reading,Writing=Writing,
            Speaking=Speaking,Listening=Listening)
Observables <- lapply(EMs,RNetica::NetworkAllNodes)
```


# Parameterizing the CPTs

```{r}
for (prof in Proficiencies) {
  prof <- as.Pnode(prof)
  PnodeStateValues(prof) <- effectiveThetas(PnodeNumStates(prof))
  PnodeQ(prof) <- TRUE
  PnodeLink(prof) <- "normalLink"
  PnodeRules(prof) <- "Compensatory"
  PnodeAlphas(prof) <- PnodeDefaultAlphas(prof)
  PnodeBetas(prof) <- PnodeDefaultBetas(prof)
  PnodeLinkScale(prof) <- .01
}  
```



# Building Manifests

# Building the Omega and Q matrixes

# Building the Statistics